// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/src/ReasonReact.js");
var GuesstimateInputJs = require("./GuesstimateInput.js");

function fn(a) {
  return /* () */0;
}

var guesstimateInput = GuesstimateInputJs.GuesstimateInput;

function make($staropt$star, $staropt$star$1, $staropt$star$2, children) {
  var sampleCount = $staropt$star !== undefined ? $staropt$star : 10000;
  var onUpdate = $staropt$star$1 !== undefined ? $staropt$star$1 : fn;
  var focusOnRender = $staropt$star$2 !== undefined ? $staropt$star$2 : true;
  return ReasonReact.wrapJsForReason(guesstimateInput, {
              sampleCount: sampleCount,
              onUpdate: onUpdate,
              focusOnRender: focusOnRender
            }, children);
}

exports.fn = fn;
exports.guesstimateInput = guesstimateInput;
exports.make = make;
/* guesstimateInput Not a pure module */
