module.exports = {
  // Server is ready
  SERVER_IS_READY: 'SERVER_IS_READY',

  // Sync Signals
  EVERY_HOUR: 'EVERY_HOUR',
  EVERY_TEN_MINUTES: 'EVERY_TEN_MINUTES',
  EVERY_MINUTE: 'EVERY_MINUTE',

  // Encapsulated Events Flow
  MAIL: 'MAIL',

  // System Events
  NEW_MEASUREMENT: 'NEW_MEASUREMENT',
  NEW_MEASURABLE: 'NEW_MEASURABLE',
  NEW_MEMBERSHIP: 'NEW_MEMBERSHIP',
  NEW_CHANNEL: 'NEW_CHANNEL',
  NEW_SERIES: 'NEW_SERIES',
  NEW_INVITATION: 'NEW_INVITATION',

  MEASURABLE_CHANGED: 'MEASURABLE_CHANGED',
};
