// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Home$Client = require("./pages/Home.bs.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var User$Client = require("./pages/User.bs.js");
var Users$Client = require("./pages/Users.bs.js");
var Agents$Client = require("./pages/Agents.bs.js");
var Measurable$Client = require("./pages/Measurable/Measurable.bs.js");
var Measurables$Client = require("./pages/Measurables.bs.js");
var PaddedLayout$Client = require("./utils/PaddedLayout.bs.js");

require('../node_modules/handsontable/dist/handsontable.full.css');
;

function reducer(action, _) {
  return /* Update */Block.__(0, [/* record */[/* route */action[0]]]);
}

function mapUrlToRoute(url) {
  var match = url[/* path */0];
  if (match) {
    switch (match[0]) {
      case "agents" : 
          if (match[1]) {
            return /* Home */0;
          } else {
            return /* Agents */2;
          }
      case "measurables" : 
          var match$1 = match[1];
          if (match$1) {
            if (match$1[1]) {
              return /* Home */0;
            } else {
              return /* Measurable */Block.__(1, [match$1[0]]);
            }
          } else {
            return /* Measurables */3;
          }
      case "users" : 
          var match$2 = match[1];
          if (match$2) {
            if (match$2[1]) {
              return /* Home */0;
            } else {
              return /* User */Block.__(0, [match$2[0]]);
            }
          } else {
            return /* Users */1;
          }
      default:
        return /* Home */0;
    }
  } else {
    return /* Home */0;
  }
}

function mapUrlToAction(url) {
  return /* ChangeRoute */[mapUrlToRoute(url)];
}

var component = ReasonReact.reducerComponent("App");

function inside(r) {
  if (typeof r === "number") {
    switch (r) {
      case 0 : 
      case 1 : 
          return ReasonReact.element(undefined, undefined, Users$Client.make(/* array */[]));
      case 2 : 
          return ReasonReact.element(undefined, undefined, Agents$Client.make(/* array */[]));
      case 3 : 
          return ReasonReact.element(undefined, undefined, Measurables$Client.make(/* array */[]));
      case 4 : 
          return ReasonReact.element(undefined, undefined, Home$Client.make(/* array */[]));
      
    }
  } else if (r.tag) {
    return ReasonReact.element(undefined, undefined, Measurable$Client.make(r[0], /* array */[]));
  } else {
    return ReasonReact.element(undefined, undefined, User$Client.make(r[0], /* array */[]));
  }
}

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */(function (self) {
              var url = ReasonReact.Router[/* dangerouslyGetInitialUrl */3](/* () */0);
              Curry._1(self[/* send */3], /* ChangeRoute */[mapUrlToRoute(url)]);
              var watcherID = ReasonReact.Router[/* watchUrl */1]((function (url) {
                      return Curry._1(self[/* send */3], /* ChangeRoute */[mapUrlToRoute(url)]);
                    }));
              return Curry._1(self[/* onUnmount */4], (function () {
                            return ReasonReact.Router[/* unwatchUrl */2](watcherID);
                          }));
            }),
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              return ReasonReact.element(undefined, undefined, PaddedLayout$Client.make(/* array */[inside(self[/* state */1][/* route */0])]));
            }),
          /* initialState */(function () {
              return /* record */[/* route : Home */0];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */reducer,
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.reducer = reducer;
exports.mapUrlToRoute = mapUrlToRoute;
exports.mapUrlToAction = mapUrlToAction;
exports.component = component;
exports.inside = inside;
exports.make = make;
/*  Not a pure module */
