// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

function ste(prim) {
  return prim;
}

var component = ReasonReact.statelessComponent("User");

function link(url, name) {
  return React.createElement("a", {
              onClick: (function () {
                  return ReasonReact.Router[/* push */0](url);
                })
            }, name);
}

var header = Css.style(/* :: */[
      Css.background(Css.hex("dcdcdc")),
      /* :: */[
        Css.padding(Css.px(5)),
        /* :: */[
          Css.selector(" h4", /* :: */[
                Css.marginTop(Css.px(2)),
                /* [] */0
              ]),
          /* [] */0
        ]
      ]
    ]);

var Styles = /* module */[/* header */header];

Css.$$global("body", /* :: */[
      Css.fontFamily("Lato"),
      /* [] */0
    ]);

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("div", {
                          className: header
                        }, React.createElement("h4", undefined, "Prediction App"), link("/users", "Users"), link("/measurables", "Measurables"));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.ste = ste;
exports.component = component;
exports.link = link;
exports.Styles = Styles;
exports.make = make;
/* component Not a pure module */
