// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function factToJs(param) {
  return {
          id: param.id,
          property: param.property,
          isInversed: param.isInversed,
          value: param.value
        };
}

function factFromJs(param) {
  return {
          id: param.id,
          property: param.property,
          isInversed: param.isInversed,
          value: param.value
        };
}

function thingToJs(param) {
  return {
          id: param.id,
          facts: param.facts
        };
}

function thingFromJs(param) {
  return {
          id: param.id,
          facts: param.facts
        };
}

exports.factToJs = factToJs;
exports.factFromJs = factFromJs;
exports.thingToJs = thingToJs;
exports.thingFromJs = thingFromJs;
/* No side effect */
