// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';


function factToJs(param) {
  return {
          id: param[/* id */0],
          property: param[/* property */1],
          isInversed: param[/* isInversed */2],
          value: param[/* value */3]
        };
}

function factFromJs(param) {
  return /* record */[
          /* id */param.id,
          /* property */param.property,
          /* isInversed */param.isInversed,
          /* value */param.value
        ];
}

function thingToJs(param) {
  return {
          id: param[/* id */0],
          facts: param[/* facts */1]
        };
}

function thingFromJs(param) {
  return /* record */[
          /* id */param.id,
          /* facts */param.facts
        ];
}

exports.factToJs = factToJs;
exports.factFromJs = factFromJs;
exports.thingToJs = thingToJs;
exports.thingFromJs = thingFromJs;
/* No side effect */
