// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var JsonKeys = {
  facts: "facts",
  things: "things",
  thingIdField: "id"
};

var Value = {
  dataTypeField: "dataValue",
  dataField: "data",
  jsonType: "json",
  stringType: "string",
  thingIdType: "thingId"
};

var Fields = {
  id: "id",
  subjectId: "subjectId",
  propertyId: "propertyId",
  value: "value",
  baseId: "baseId",
  resourceId: "resourceId",
  idIsPublic: "idIsPublic"
};

var FactJson = {
  Value: Value,
  Fields: Fields
};

exports.JsonKeys = JsonKeys;
exports.FactJson = FactJson;
/* No side effect */
