// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Value$Shared = require("../../src/Value/Value.bs.js");

describe("Value", (function () {
        Jest.test("encoding / decoding", (function () {
                var toJson = Value$Shared.encodeTrio(/* record */[
                      /* p25 */1.0,
                      /* p50 */2.0,
                      /* p75 */4.1
                    ]);
                var fromJson = Value$Shared.parseTrio(toJson);
                return Jest.Expect[/* toEqual */12](4.1, Jest.Expect[/* expect */0](fromJson[/* p75 */2]));
              }));
        return Jest.test("next", (function () {
                      var toJson = Value$Shared.encodeTrio(/* record */[
                            /* p25 */1.0,
                            /* p50 */2.0,
                            /* p75 */4.1
                          ]);
                      var fromJson = Value$Shared.parseTrio(toJson);
                      return Jest.Expect[/* toEqual */12](4.1, Jest.Expect[/* expect */0](fromJson[/* p75 */2]));
                    }));
      }));

/*  Not a pure module */
