// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Json = require("@glennsl/bs-json/src/Json.bs.js");
var Block = require("bs-platform/lib/js/block.js");
var Belt_Result = require("bs-platform/lib/js/belt_Result.js");
var Value$Shared = require("../../src/Value/Value.bs.js");

describe("FloatPercentiles", (function () {
        Jest.test("#decode FloatPoint", (function () {
                return Jest.Expect[/* toEqual */12](/* Ok */Block.__(0, [/* `FloatPoint */[
                                -606499532,
                                0.3
                              ]]), Jest.Expect[/* expect */0](Value$Shared.decode(Json.parseOrRaise(" {\n        \"dataType\": \"floatPoint\",\n        \"data\": 0.3\n      } "))));
              }));
        Jest.test("#decode FloatPoint with large int", (function () {
                return Jest.Expect[/* toEqual */12](/* Ok */Block.__(0, [/* `FloatPoint */[
                                -606499532,
                                3333.0
                              ]]), Jest.Expect[/* expect */0](Value$Shared.decode(Json.parseOrRaise(" {\n        \"dataType\": \"floatPoint\",\n        \"data\": 3333\n      } "))));
              }));
        Jest.test("#decode percentage with int", (function () {
                return Jest.Expect[/* toEqual */12](/* Ok */Block.__(0, [/* `Percentage */[
                                -488794310,
                                1.0
                              ]]), Jest.Expect[/* expect */0](Value$Shared.decode(Json.parseOrRaise(" {\n        \"dataType\": \"percentagePoint\",\n        \"data\": 1\n      } "))));
              }));
        Jest.test("#decode FloatPoint", (function () {
                return Jest.Expect[/* toEqual */12](/* Ok */Block.__(0, [/* `FloatPoint */[
                                -606499532,
                                0.3
                              ]]), Jest.Expect[/* expect */0](Value$Shared.decode(Json.parseOrRaise(" {\n        \"dataType\": \"floatPoint\",\n        \"data\": 0.3\n      } "))));
              }));
        Jest.test("#isValid true", (function () {
                return Jest.Expect[/* toEqual */12](true, Jest.Expect[/* expect */0](Value$Shared.isValid(/* `FloatPercentiles */[
                                    393953338,
                                    Value$Shared.FloatPercentiles[/* fromArray */3](/* array */[
                                          /* tuple */[
                                            25.0,
                                            1.0
                                          ],
                                          /* tuple */[
                                            50.0,
                                            3.0
                                          ],
                                          /* tuple */[
                                            75.0,
                                            10.0
                                          ]
                                        ])
                                  ])));
              }));
        Jest.test("#isValid false", (function () {
                return Jest.Expect[/* toEqual */12](false, Jest.Expect[/* expect */0](Value$Shared.isValid(/* `FloatPercentiles */[
                                    393953338,
                                    Value$Shared.FloatPercentiles[/* fromArray */3](/* array */[
                                          /* tuple */[
                                            25.0,
                                            1.0
                                          ],
                                          /* tuple */[
                                            50.0,
                                            3.0
                                          ],
                                          /* tuple */[
                                            78.0,
                                            10.0
                                          ]
                                        ])
                                  ])));
              }));
        return Jest.test("#encode", (function () {
                      var json = Json.parseOrRaise(" {\n        \"dataType\": \"floatPercentiles\",\n        \"data\":   { \"25.\": 1.0, \"50.\": 3.0, \"75.\":10.0 }\n      } ");
                      return Jest.Expect[/* toEqual */12](json, Jest.Expect[/* expect */0](Value$Shared.encode(/* `FloatPercentiles */[
                                          393953338,
                                          Value$Shared.FloatPercentiles[/* fromArray */3](/* array */[
                                                /* tuple */[
                                                  25.0,
                                                  1.0
                                                ],
                                                /* tuple */[
                                                  50.0,
                                                  3.0
                                                ],
                                                /* tuple */[
                                                  75.0,
                                                  10.0
                                                ]
                                              ])
                                        ])));
                    }));
      }));

describe("Value", (function () {
        return Jest.test("#encode DateTimePercentiles", (function () {
                      var json = Json.parseOrRaise(" {\n        \"dataType\": \"floatPercentiles\",\n        \"data\":   { \"25.\": 1.0, \"50.\": 3.0, \"75.\":10.0 }\n      } ");
                      var floatPercentiles = Value$Shared.FloatPercentiles[/* fromArray */3](/* array */[
                            /* tuple */[
                              25.0,
                              1.0
                            ],
                            /* tuple */[
                              50.0,
                              3.0
                            ],
                            /* tuple */[
                              75.0,
                              10.0
                            ]
                          ]);
                      var value = /* `FloatPercentiles */[
                        393953338,
                        floatPercentiles
                      ];
                      return Jest.Expect[/* toEqual */12](json, Jest.Expect[/* expect */0](Value$Shared.encode(value)));
                    }));
      }));

Jest.test("#decode DateTimePercentiles", (function () {
        var json = Json.parseOrRaise(" {\n         \"dataType\": \"floatPercentiles\",\n         \"data\":   { \"25.\": 1.0, \"50.\": 3.0, \"75.\":10.0 }\n       } ");
        var floatPercentiles = Value$Shared.FloatPercentiles[/* fromArray */3](/* array */[
              /* tuple */[
                25.0,
                1.0
              ],
              /* tuple */[
                50.0,
                3.0
              ],
              /* tuple */[
                75.0,
                10.0
              ]
            ]);
        var value = /* `FloatPercentiles */[
          393953338,
          floatPercentiles
        ];
        return Jest.Expect[/* toEqual */12](/* Ok */Block.__(0, [value]), Jest.Expect[/* expect */0](Value$Shared.decode(json)));
      }));

Jest.test("#decode with Error", (function () {
        var json = Json.parseOrRaise(" {\n         \"dataType\": \"floatPercentiles\",\n         \"data\":   { \"25.\": \"sdf\", \"50.\": 3.0, \"75.\":10.0 }\n       } ");
        return Jest.Expect[/* toEqual */12](true, Jest.Expect[/* expect */0](Belt_Result.isError(Value$Shared.decode(json))));
      }));

/*  Not a pure module */
