const TEMPLATE_NAME = {
  MEASURABLE_STATE_IS_CHANGED: 'MEASURABLE_STATE_IS_CHANGED',
  MEASURABLE_STATE_IS_RESOLVED: 'MEASURABLE_STATE_IS_RESOLVED',
  MEMBER_ADDED_TO_COMMUNITY: 'MEMBER_ADDED_TO_COMMUNITY',
  MEMBER_INVITED_TO_COMMUNITY: 'MEMBER_INVITED_TO_COMMUNITY',

  MEMBER_JOINED_TO_COMMUNITY_FEED_ITEM: 'MEMBER_JOINED_TO_COMMUNITY_FEED_ITEM',
};

module.exports = {
  TEMPLATE_NAME,
};
