// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");
var Json_encode = require("@glennsl/bs-json/src/Json_encode.bs.js");
var Config$BsKen = require("../Config.bs.js");
var Graph_Value$BsKen = require("./Graph_Value.bs.js");

function subjectId(t) {
  return t.subjectId;
}

function propertyId(t) {
  return t.propertyId;
}

function edgeId(edge) {
  var match = edge === /* SUBJECT */0;
  if (match) {
    return subjectId;
  } else {
    return propertyId;
  }
}

function value(t) {
  return t.value;
}

function id(t) {
  return t.thingIdString;
}

function to_json(t) {
  return Json_encode.object_(/* :: */[
              /* tuple */[
                Config$BsKen.FactJson.Fields.id,
                t.thingIdString
              ],
              /* :: */[
                /* tuple */[
                  Config$BsKen.FactJson.Fields.subjectId,
                  t.subjectId
                ],
                /* :: */[
                  /* tuple */[
                    Config$BsKen.FactJson.Fields.propertyId,
                    t.propertyId
                  ],
                  /* :: */[
                    /* tuple */[
                      Config$BsKen.FactJson.Fields.value,
                      Graph_Value$BsKen.to_json(t.value)
                    ],
                    /* [] */0
                  ]
                ]
              ]
            ]);
}

function from_json(t) {
  return {
          thingIdString: Json_decode.field(Config$BsKen.FactJson.Fields.id, Json_decode.string, t),
          subjectId: Json_decode.field(Config$BsKen.FactJson.Fields.subjectId, Json_decode.string, t),
          propertyId: Json_decode.field(Config$BsKen.FactJson.Fields.propertyId, Json_decode.string, t),
          value: {
            valueType: Json_decode.field(Config$BsKen.FactJson.Fields.value, Graph_Value$BsKen.from_json, t)
          }
        };
}

exports.subjectId = subjectId;
exports.propertyId = propertyId;
exports.edgeId = edgeId;
exports.value = value;
exports.id = id;
exports.to_json = to_json;
exports.from_json = from_json;
/* No side effect */
