// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");
var Json_encode = require("@glennsl/bs-json/src/Json_encode.bs.js");
var Config$BsKen = require("../Config.bs.js");

function to_json(v) {
  var match = v.valueType;
  switch (match.tag | 0) {
    case /* String */0 :
        return Json_encode.object_(/* :: */[
                    /* tuple */[
                      Config$BsKen.FactJson.Value.dataTypeField,
                      Config$BsKen.FactJson.Value.stringType
                    ],
                    /* :: */[
                      /* tuple */[
                        Config$BsKen.FactJson.Value.dataField,
                        match[0]
                      ],
                      /* [] */0
                    ]
                  ]);
    case /* ThingId */1 :
        return Json_encode.object_(/* :: */[
                    /* tuple */[
                      Config$BsKen.FactJson.Value.dataTypeField,
                      Config$BsKen.FactJson.Value.thingIdType
                    ],
                    /* :: */[
                      /* tuple */[
                        Config$BsKen.FactJson.Value.dataField,
                        match[0]
                      ],
                      /* [] */0
                    ]
                  ]);
    case /* JSON */2 :
        return Json_encode.object_(/* :: */[
                    /* tuple */[
                      Config$BsKen.FactJson.Value.dataTypeField,
                      Config$BsKen.FactJson.Value.jsonType
                    ],
                    /* :: */[
                      /* tuple */[
                        Config$BsKen.FactJson.Value.dataField,
                        match[0]
                      ],
                      /* [] */0
                    ]
                  ]);
    
  }
}

function from_json(v) {
  var _type = Json_decode.field(Config$BsKen.FactJson.Value.dataTypeField, Json_decode.string, v);
  switch (_type) {
    case "string" :
        return /* String */Block.__(0, [Json_decode.field(Config$BsKen.FactJson.Value.dataField, Json_decode.string, v)]);
    case "thingId" :
        return /* ThingId */Block.__(1, [Json_decode.field(Config$BsKen.FactJson.Value.dataField, Json_decode.string, v)]);
    default:
      return /* ThingId */Block.__(1, [Json_decode.field(Config$BsKen.FactJson.Value.dataField, Json_decode.string, v)]);
  }
}

exports.to_json = to_json;
exports.from_json = from_json;
/* No side effect */
