// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("MeasurableChart");

function toUnix(x) {
  return x.createdAt.unix();
}

var plot = Css.style(/* :: */[
      Css.maxWidth(Css.px(800)),
      /* [] */0
    ]);

var Styles = /* module */[/* plot */plot];

exports.component = component;
exports.toUnix = toUnix;
exports.Styles = Styles;
/* component Not a pure module */
