// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");

function parseTrio(json) {
  return /* record */[
          /* p25 */Json_decode.field("p25", Json_decode.$$float, json),
          /* p50 */Json_decode.field("p50", Json_decode.$$float, json),
          /* p75 */Json_decode.field("p75", Json_decode.$$float, json)
        ];
}

function parseValue(json) {
  return /* record */[
          /* trio */Json_decode.optional((function (param) {
                  return Json_decode.field("trio", parseTrio, param);
                }), json),
          /* pointEstimate */Json_decode.optional((function (param) {
                  return Json_decode.field("pointEstimate", Json_decode.$$float, param);
                }), json)
        ];
}

exports.parseTrio = parseTrio;
exports.parseValue = parseValue;
/* No side effect */
