// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Js_exn = require("bs-platform/lib/js/js_exn.js");
var Js_dict = require("bs-platform/lib/js/js_dict.js");
var Js_json = require("bs-platform/lib/js/js_json.js");
var MomentRe = require("bs-moment/src/MomentRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");
var ReasonApollo = require("reason-apollo/src/ReasonApollo.bs.js");
var Utils$Client = require("../../utils/Utils.bs.js");
var Queries$Client = require("../Queries.bs.js");
var Result$Rationale = require("rationale/src/Result.js");
var Function$Rationale = require("rationale/src/Function.js");
var MeasurableChart$Client = require("./MeasurableChart.bs.js");
var MeasurableTable$Client = require("./MeasurableTable.bs.js");
var MeasurableTypes$Client = require("./MeasurableTypes.bs.js");

var partial_arg = Function$Rationale.Infix[/* ||> */1];

function toMoment(param) {
  return partial_arg(Queries$Client.jsonToString, (function (eta) {
                return MomentRe.moment(undefined, eta);
              }), param);
}

function toOptionalMoment(e) {
  var eta = e !== undefined ? Queries$Client.jsonToString(Js_primitive.valFromOption(e)) : "";
  return MomentRe.moment(undefined, eta);
}

var ppx_printed_query = "query getMeasurable($id: String!)  {\nmeasurable: measurable(id: $id)  {\nid  \nname  \nvalueType  \nisLocked  \ncreatedAt  \nmeasurements: Measurements  {\ncreatedAt  \nvalue  \ncompetitorType  \ntaggedMeasurementId  \nrelevantAt  \nagent: Agent  {\nid  \nuser: User  {\nid  \nname  \n}\n\nbot: Bot  {\nid  \nname  \ncompetitorType  \n}\n\n}\n\n}\n\n}\n\n}\n";

function parse(value) {
  var match = Js_json.decodeObject(value);
  if (match !== undefined) {
    var match$1 = Js_primitive.valFromOption(match)["measurable"];
    var tmp;
    if (match$1 !== undefined) {
      var match$2 = Js_json.decodeNull(match$1);
      if (match$2 !== undefined) {
        tmp = undefined;
      } else {
        var match$3 = Js_json.decodeObject(match$1);
        var tmp$1;
        if (match$3 !== undefined) {
          var value$1 = Js_primitive.valFromOption(match$3);
          var match$4 = value$1["id"];
          var tmp$2;
          if (match$4 !== undefined) {
            var match$5 = Js_json.decodeString(match$4);
            tmp$2 = match$5 !== undefined ? match$5 : Js_exn.raiseError("graphql_ppx: Expected string, got " + JSON.stringify(match$4));
          } else {
            tmp$2 = Js_exn.raiseError("graphql_ppx: Field id on type Measurable is missing");
          }
          var match$6 = value$1["name"];
          var tmp$3;
          if (match$6 !== undefined) {
            var match$7 = Js_json.decodeString(match$6);
            tmp$3 = match$7 !== undefined ? match$7 : Js_exn.raiseError("graphql_ppx: Expected string, got " + JSON.stringify(match$6));
          } else {
            tmp$3 = Js_exn.raiseError("graphql_ppx: Field name on type Measurable is missing");
          }
          var match$8 = value$1["valueType"];
          var tmp$4;
          if (match$8 !== undefined) {
            var match$9 = Js_json.decodeString(match$8);
            if (match$9 !== undefined) {
              var value$2 = match$9;
              switch (value$2) {
                case "DATE" : 
                    tmp$4 = /* DATE */757341742;
                    break;
                case "FLOAT" : 
                    tmp$4 = /* FLOAT */8715644;
                    break;
                case "PERCENTAGE" : 
                    tmp$4 = /* PERCENTAGE */-566884582;
                    break;
                default:
                  tmp$4 = Js_exn.raiseError("graphql_ppx: Unknown enum variant for MeasurablevalueTypeEnumType: " + value$2);
              }
            } else {
              tmp$4 = Js_exn.raiseError("graphql_ppx: Expected enum value for MeasurablevalueTypeEnumType, got " + JSON.stringify(match$8));
            }
          } else {
            tmp$4 = Js_exn.raiseError("graphql_ppx: Field valueType on type Measurable is missing");
          }
          var match$10 = value$1["isLocked"];
          var tmp$5;
          if (match$10 !== undefined) {
            var match$11 = Js_json.decodeBoolean(match$10);
            tmp$5 = match$11 !== undefined ? match$11 : Js_exn.raiseError("graphql_ppx: Expected boolean, got " + JSON.stringify(match$10));
          } else {
            tmp$5 = Js_exn.raiseError("graphql_ppx: Field isLocked on type Measurable is missing");
          }
          var match$12 = value$1["createdAt"];
          var match$13 = value$1["measurements"];
          var tmp$6;
          if (match$13 !== undefined) {
            var match$14 = Js_json.decodeArray(match$13);
            tmp$6 = match$14 !== undefined ? match$14.map((function (value) {
                      var match = Js_json.decodeNull(value);
                      if (match !== undefined) {
                        return undefined;
                      } else {
                        var match$1 = Js_json.decodeObject(value);
                        var tmp;
                        if (match$1 !== undefined) {
                          var value$1 = Js_primitive.valFromOption(match$1);
                          var match$2 = value$1["createdAt"];
                          var match$3 = value$1["value"];
                          var match$4 = value$1["competitorType"];
                          var tmp$1;
                          if (match$4 !== undefined) {
                            var match$5 = Js_json.decodeString(match$4);
                            if (match$5 !== undefined) {
                              var value$2 = match$5;
                              switch (value$2) {
                                case "AGGREGATION" : 
                                    tmp$1 = /* AGGREGATION */497422978;
                                    break;
                                case "COMPETITIVE" : 
                                    tmp$1 = /* COMPETITIVE */-288189265;
                                    break;
                                case "OBJECTIVE" : 
                                    tmp$1 = /* OBJECTIVE */1055622745;
                                    break;
                                default:
                                  tmp$1 = Js_exn.raiseError("graphql_ppx: Unknown enum variant for competitorType: " + value$2);
                              }
                            } else {
                              tmp$1 = Js_exn.raiseError("graphql_ppx: Expected enum value for competitorType, got " + JSON.stringify(match$4));
                            }
                          } else {
                            tmp$1 = Js_exn.raiseError("graphql_ppx: Field competitorType on type Measurement is missing");
                          }
                          var match$6 = value$1["taggedMeasurementId"];
                          var tmp$2;
                          if (match$6 !== undefined) {
                            var match$7 = Js_json.decodeNull(match$6);
                            if (match$7 !== undefined) {
                              tmp$2 = undefined;
                            } else {
                              var match$8 = Js_json.decodeString(match$6);
                              tmp$2 = match$8 !== undefined ? match$8 : Js_exn.raiseError("graphql_ppx: Expected string, got " + JSON.stringify(match$6));
                            }
                          } else {
                            tmp$2 = undefined;
                          }
                          var match$9 = value$1["relevantAt"];
                          var tmp$3;
                          if (match$9 !== undefined) {
                            var match$10 = Js_json.decodeNull(match$9);
                            tmp$3 = toOptionalMoment(match$10 !== undefined ? undefined : Js_primitive.some(match$9));
                          } else {
                            tmp$3 = Js_exn.raiseError("graphql_ppx: Field relevantAt on type Measurement is missing");
                          }
                          var match$11 = value$1["agent"];
                          var tmp$4;
                          if (match$11 !== undefined) {
                            var match$12 = Js_json.decodeNull(match$11);
                            if (match$12 !== undefined) {
                              tmp$4 = undefined;
                            } else {
                              var match$13 = Js_json.decodeObject(match$11);
                              var tmp$5;
                              if (match$13 !== undefined) {
                                var value$3 = Js_primitive.valFromOption(match$13);
                                var match$14 = value$3["id"];
                                var tmp$6;
                                if (match$14 !== undefined) {
                                  var match$15 = Js_json.decodeString(match$14);
                                  tmp$6 = match$15 !== undefined ? match$15 : Js_exn.raiseError("graphql_ppx: Expected string, got " + JSON.stringify(match$14));
                                } else {
                                  tmp$6 = Js_exn.raiseError("graphql_ppx: Field id on type Agent is missing");
                                }
                                var match$16 = value$3["user"];
                                var tmp$7;
                                if (match$16 !== undefined) {
                                  var match$17 = Js_json.decodeNull(match$16);
                                  if (match$17 !== undefined) {
                                    tmp$7 = undefined;
                                  } else {
                                    var match$18 = Js_json.decodeObject(match$16);
                                    var tmp$8;
                                    if (match$18 !== undefined) {
                                      var value$4 = Js_primitive.valFromOption(match$18);
                                      var match$19 = value$4["id"];
                                      var tmp$9;
                                      if (match$19 !== undefined) {
                                        var match$20 = Js_json.decodeString(match$19);
                                        tmp$9 = match$20 !== undefined ? match$20 : Js_exn.raiseError("graphql_ppx: Expected string, got " + JSON.stringify(match$19));
                                      } else {
                                        tmp$9 = Js_exn.raiseError("graphql_ppx: Field id on type User is missing");
                                      }
                                      var match$21 = value$4["name"];
                                      var tmp$10;
                                      if (match$21 !== undefined) {
                                        var match$22 = Js_json.decodeString(match$21);
                                        tmp$10 = match$22 !== undefined ? match$22 : Js_exn.raiseError("graphql_ppx: Expected string, got " + JSON.stringify(match$21));
                                      } else {
                                        tmp$10 = Js_exn.raiseError("graphql_ppx: Field name on type User is missing");
                                      }
                                      tmp$8 = {
                                        id: tmp$9,
                                        name: tmp$10
                                      };
                                    } else {
                                      tmp$8 = Js_exn.raiseError("graphql_ppx: Object is not a value");
                                    }
                                    tmp$7 = Js_primitive.some(tmp$8);
                                  }
                                } else {
                                  tmp$7 = undefined;
                                }
                                var match$23 = value$3["bot"];
                                var tmp$11;
                                if (match$23 !== undefined) {
                                  var match$24 = Js_json.decodeNull(match$23);
                                  if (match$24 !== undefined) {
                                    tmp$11 = undefined;
                                  } else {
                                    var match$25 = Js_json.decodeObject(match$23);
                                    var tmp$12;
                                    if (match$25 !== undefined) {
                                      var value$5 = Js_primitive.valFromOption(match$25);
                                      var match$26 = value$5["id"];
                                      var tmp$13;
                                      if (match$26 !== undefined) {
                                        var match$27 = Js_json.decodeString(match$26);
                                        tmp$13 = match$27 !== undefined ? match$27 : Js_exn.raiseError("graphql_ppx: Expected string, got " + JSON.stringify(match$26));
                                      } else {
                                        tmp$13 = Js_exn.raiseError("graphql_ppx: Field id on type Bot is missing");
                                      }
                                      var match$28 = value$5["name"];
                                      var tmp$14;
                                      if (match$28 !== undefined) {
                                        var match$29 = Js_json.decodeNull(match$28);
                                        if (match$29 !== undefined) {
                                          tmp$14 = undefined;
                                        } else {
                                          var match$30 = Js_json.decodeString(match$28);
                                          tmp$14 = match$30 !== undefined ? match$30 : Js_exn.raiseError("graphql_ppx: Expected string, got " + JSON.stringify(match$28));
                                        }
                                      } else {
                                        tmp$14 = undefined;
                                      }
                                      var match$31 = value$5["competitorType"];
                                      var tmp$15;
                                      if (match$31 !== undefined) {
                                        var match$32 = Js_json.decodeString(match$31);
                                        if (match$32 !== undefined) {
                                          var value$6 = match$32;
                                          switch (value$6) {
                                            case "AGGREGATION" : 
                                                tmp$15 = /* AGGREGATION */497422978;
                                                break;
                                            case "COMPETITIVE" : 
                                                tmp$15 = /* COMPETITIVE */-288189265;
                                                break;
                                            case "OBJECTIVE" : 
                                                tmp$15 = /* OBJECTIVE */1055622745;
                                                break;
                                            default:
                                              tmp$15 = Js_exn.raiseError("graphql_ppx: Unknown enum variant for competitorType: " + value$6);
                                          }
                                        } else {
                                          tmp$15 = Js_exn.raiseError("graphql_ppx: Expected enum value for competitorType, got " + JSON.stringify(match$31));
                                        }
                                      } else {
                                        tmp$15 = Js_exn.raiseError("graphql_ppx: Field competitorType on type Bot is missing");
                                      }
                                      tmp$12 = {
                                        id: tmp$13,
                                        name: tmp$14,
                                        competitorType: tmp$15
                                      };
                                    } else {
                                      tmp$12 = Js_exn.raiseError("graphql_ppx: Object is not a value");
                                    }
                                    tmp$11 = Js_primitive.some(tmp$12);
                                  }
                                } else {
                                  tmp$11 = undefined;
                                }
                                tmp$5 = {
                                  id: tmp$6,
                                  user: tmp$7,
                                  bot: tmp$11
                                };
                              } else {
                                tmp$5 = Js_exn.raiseError("graphql_ppx: Object is not a value");
                              }
                              tmp$4 = Js_primitive.some(tmp$5);
                            }
                          } else {
                            tmp$4 = undefined;
                          }
                          tmp = {
                            createdAt: match$2 !== undefined ? toMoment(match$2) : Js_exn.raiseError("graphql_ppx: Field createdAt on type Measurement is missing"),
                            value: match$3 !== undefined ? MeasurableTypes$Client.parseValue(match$3) : Js_exn.raiseError("graphql_ppx: Field value on type Measurement is missing"),
                            competitorType: tmp$1,
                            taggedMeasurementId: tmp$2,
                            relevantAt: tmp$3,
                            agent: tmp$4
                          };
                        } else {
                          tmp = Js_exn.raiseError("graphql_ppx: Object is not a value");
                        }
                        return Js_primitive.some(tmp);
                      }
                    })) : Js_exn.raiseError("graphql_ppx: Expected array, got " + JSON.stringify(match$13));
          } else {
            tmp$6 = Js_exn.raiseError("graphql_ppx: Field measurements on type Measurable is missing");
          }
          tmp$1 = {
            id: tmp$2,
            name: tmp$3,
            valueType: tmp$4,
            isLocked: tmp$5,
            createdAt: match$12 !== undefined ? toMoment(match$12) : Js_exn.raiseError("graphql_ppx: Field createdAt on type Measurable is missing"),
            measurements: tmp$6
          };
        } else {
          tmp$1 = Js_exn.raiseError("graphql_ppx: Object is not a value");
        }
        tmp = Js_primitive.some(tmp$1);
      }
    } else {
      tmp = undefined;
    }
    return {
            measurable: tmp
          };
  } else {
    return Js_exn.raiseError("graphql_ppx: Object is not a value");
  }
}

function make(id, _) {
  return {
          query: ppx_printed_query,
          variables: Js_dict.fromArray(/* array */[/* tuple */[
                  "id",
                  id
                ]]),
          parse: parse
        };
}

function makeWithVariables(variables) {
  var id = variables.id;
  return {
          query: ppx_printed_query,
          variables: Js_dict.fromArray(/* array */[/* tuple */[
                  "id",
                  id
                ]]),
          parse: parse
        };
}

function ret_type() {
  return /* module */[];
}

var MT_Ret = /* module */[];

var GetMeasurable = /* module */[
  /* ppx_printed_query */ppx_printed_query,
  /* query */ppx_printed_query,
  /* parse */parse,
  /* make */make,
  /* makeWithVariables */makeWithVariables,
  /* ret_type */ret_type,
  /* MT_Ret */MT_Ret
];

var ppx_printed_query$1 = "mutation createMeasurement($value: SequelizeJSON!, $competitorType: competitorType!, $measurableId: String!, $agentId: String!)  {\ncreateMeasurement(value: $value, competitorType: $competitorType, measurableId: $measurableId, agentId: $agentId)  {\ncreatedAt  \n}\n\n}\n";

function parse$1(value) {
  var match = Js_json.decodeObject(value);
  if (match !== undefined) {
    var match$1 = Js_primitive.valFromOption(match)["createMeasurement"];
    var tmp;
    if (match$1 !== undefined) {
      var match$2 = Js_json.decodeNull(match$1);
      if (match$2 !== undefined) {
        tmp = undefined;
      } else {
        var match$3 = Js_json.decodeObject(match$1);
        var tmp$1;
        if (match$3 !== undefined) {
          var match$4 = Js_primitive.valFromOption(match$3)["createdAt"];
          tmp$1 = {
            createdAt: match$4 !== undefined ? match$4 : Js_exn.raiseError("graphql_ppx: Field createdAt on type Measurement is missing")
          };
        } else {
          tmp$1 = Js_exn.raiseError("graphql_ppx: Object is not a value");
        }
        tmp = Js_primitive.some(tmp$1);
      }
    } else {
      tmp = undefined;
    }
    return {
            createMeasurement: tmp
          };
  } else {
    return Js_exn.raiseError("graphql_ppx: Object is not a value");
  }
}

function json_of_competitorType(value) {
  if (value !== 497422978) {
    if (value >= 1055622745) {
      return "OBJECTIVE";
    } else {
      return "COMPETITIVE";
    }
  } else {
    return "AGGREGATION";
  }
}

function make$1(value, competitorType, measurableId, agentId, _) {
  return {
          query: ppx_printed_query$1,
          variables: Js_dict.fromArray(/* array */[
                /* tuple */[
                  "value",
                  value
                ],
                /* tuple */[
                  "competitorType",
                  json_of_competitorType(competitorType)
                ],
                /* tuple */[
                  "measurableId",
                  measurableId
                ],
                /* tuple */[
                  "agentId",
                  agentId
                ]
              ]),
          parse: parse$1
        };
}

function makeWithVariables$1(variables) {
  var value = variables.value;
  var competitorType = variables.competitorType;
  var measurableId = variables.measurableId;
  var agentId = variables.agentId;
  return {
          query: ppx_printed_query$1,
          variables: Js_dict.fromArray(/* array */[
                /* tuple */[
                  "value",
                  value
                ],
                /* tuple */[
                  "competitorType",
                  json_of_competitorType(competitorType)
                ],
                /* tuple */[
                  "measurableId",
                  measurableId
                ],
                /* tuple */[
                  "agentId",
                  agentId
                ]
              ]),
          parse: parse$1
        };
}

function ret_type$1() {
  return /* module */[];
}

var MT_Ret$1 = /* module */[];

var CreateMeasurement = /* module */[
  /* ppx_printed_query */ppx_printed_query$1,
  /* query */ppx_printed_query$1,
  /* parse */parse$1,
  /* json_of_competitorType */json_of_competitorType,
  /* make */make$1,
  /* makeWithVariables */makeWithVariables$1,
  /* ret_type */ret_type$1,
  /* MT_Ret */MT_Ret$1
];

var GetMeasurableQuery = ReasonApollo.CreateQuery([
      ppx_printed_query,
      parse
    ]);

var CreateMeasurementMutation = ReasonApollo.CreateMutation([
      ppx_printed_query$1,
      parse$1
    ]);

var component = ReasonReact.statelessComponent("Measurable");

function valueString(e) {
  if (e !== 8715644) {
    if (e >= 757341742) {
      return "Date";
    } else {
      return "Percentage";
    }
  } else {
    return "Float";
  }
}

function make$2(id, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              var query = make(id, /* () */0);
              var eta = Curry.app(GetMeasurableQuery[/* make */3], [
                    Js_primitive.some(query.variables),
                    50000,
                    undefined,
                    undefined,
                    undefined,
                    undefined,
                    undefined,
                    undefined,
                    undefined,
                    (function (param) {
                        return Result$Rationale.result(Utils$Client.idd, Utils$Client.idd, Curry._2(Result$Rationale.Infix[/* <$> */1], Curry._2(Result$Rationale.Infix[/* >>= */0], Utils$Client.apolloResponseToResult(param[/* result */0]), (function (e) {
                                              return Utils$Client.filterOptionalResult(Utils$Client.ste("Measurable not found"), e.measurable);
                                            })), (function (e) {
                                          var match = e.isLocked;
                                          return React.createElement("div", undefined, React.createElement("h2", undefined, e.name), React.createElement("h3", undefined, match ? "Locked: True" : "Locked: False"), ReasonReact.element(undefined, undefined, Curry._4(CreateMeasurementMutation[/* make */4], undefined, undefined, undefined, (function (mutation, _) {
                                                                var mut = make$1(MeasurableTypes$Client.encodeValue(/* record */[
                                                                          /* trio *//* record */[
                                                                            /* p25 */110.0,
                                                                            /* p50 */170.0,
                                                                            /* p75 */220.0
                                                                          ],
                                                                          /* pointEstimate */undefined
                                                                        ]), /* COMPETITIVE */-288189265, e.id, "c4aefed8-83c1-422d-9364-313071287758", /* () */0);
                                                                return React.createElement("div", undefined, React.createElement("h3", {
                                                                                onClick: (function () {
                                                                                    Curry._3(mutation, Js_primitive.some(mut.variables), /* array */["getMeasurable"], /* () */0);
                                                                                    return /* () */0;
                                                                                  })
                                                                              }, valueString(e.valueType)), ReasonReact.element(undefined, undefined, MeasurableChart$Client.make(e.measurements, /* array */[])), ReasonReact.element(undefined, undefined, MeasurableTable$Client.make(e.measurements, /* array */[])));
                                                              }))));
                                        })));
                      })
                  ]);
              return React.createElement("div", undefined, ReasonReact.element(undefined, undefined, eta));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.toMoment = toMoment;
exports.toOptionalMoment = toOptionalMoment;
exports.GetMeasurable = GetMeasurable;
exports.CreateMeasurement = CreateMeasurement;
exports.GetMeasurableQuery = GetMeasurableQuery;
exports.CreateMeasurementMutation = CreateMeasurementMutation;
exports.component = component;
exports.valueString = valueString;
exports.make = make$2;
/* GetMeasurableQuery Not a pure module */
