// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");
var Utils$Client = require("../utils/Utils.bs.js");
var Queries$Client = require("./Queries.bs.js");
var Result$Rationale = require("rationale/src/Result.js");
var Function$Rationale = require("rationale/src/Function.js");

var component = ReasonReact.statelessComponent("User");

function make(id, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              var query = Queries$Client.GetUser[/* make */3](id, /* () */0);
              var eta = Curry.app(Queries$Client.GetUserQuery[/* make */3], [
                    Js_primitive.some(query.variables),
                    undefined,
                    undefined,
                    undefined,
                    undefined,
                    undefined,
                    undefined,
                    undefined,
                    undefined,
                    (function (param) {
                        var partial_arg = Utils$Client.ste("not found");
                        var partial_arg$1 = function (param) {
                          return Utils$Client.filterOptionalResult(partial_arg, param);
                        };
                        var partial_arg$2 = Function$Rationale.Infix[/* ||> */1];
                        return Result$Rationale.result(Utils$Client.idd, Utils$Client.idd, Curry._2(Result$Rationale.Infix[/* <$> */1], Curry._2(Result$Rationale.Infix[/* >>= */0], Utils$Client.apolloResponseToResult(param[/* result */0]), (function (param) {
                                              return partial_arg$2((function (e) {
                                                            return e.user;
                                                          }), partial_arg$1, param);
                                            })), (function (e) {
                                          return Utils$Client.ste(e.name);
                                        })));
                      })
                  ]);
              return React.createElement("div", undefined, React.createElement("h2", undefined, "User Page"), ReasonReact.element(undefined, undefined, eta));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
