// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Js_dict = require("bs-platform/lib/js/js_dict.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var React = require("@handsontable/react");

function makeColumn(data, $staropt$star, $staropt$star$1, _) {
  var renderer = $staropt$star !== undefined ? $staropt$star : "text";
  var readOnly = $staropt$star$1 !== undefined ? $staropt$star$1 : true;
  return {
          data: data,
          renderer: renderer,
          readOnly: readOnly
        };
}

var foo = /* array */[Js_dict.fromList(/* :: */[
        /* tuple */[
          "aa",
          "bar"
        ],
        /* :: */[
          /* tuple */[
            "bb",
            "charr"
          ],
          /* [] */0
        ]
      ])];

var bar = /* array */[
  (function (param) {
      return {
              data: "aa",
              renderer: param,
              readOnly: true
            };
    }),
  (function (param) {
      return {
              data: "bb",
              renderer: param,
              readOnly: true
            };
    })
];

function make(data, columns, colHeaders, children) {
  return ReasonReact.wrapJsForReason(React.HotTable, {
              data: data,
              columns: columns,
              colHeaders: colHeaders,
              rowHeaders: true,
              columnSorting: true,
              sortIndicator: true,
              width: "1000",
              height: "800",
              stretchH: "all"
            }, children);
}

exports.makeColumn = makeColumn;
exports.foo = foo;
exports.bar = bar;
exports.make = make;
/* foo Not a pure module */
