// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/src/ReasonReact.js");
var React = require("@handsontable/react");

function makeColumn(data, $staropt$star, $staropt$star$1, _) {
  var renderer = $staropt$star !== undefined ? $staropt$star : "text";
  var readOnly = $staropt$star$1 !== undefined ? $staropt$star$1 : true;
  return {
          data: data,
          renderer: renderer,
          readOnly: readOnly
        };
}

function make(data, columns, colHeaders, children) {
  return ReasonReact.wrapJsForReason(React.HotTable, {
              data: data,
              columns: columns,
              colHeaders: colHeaders,
              rowHeaders: true,
              columnSorting: true,
              sortIndicator: true,
              stretchH: "all"
            }, children);
}

exports.makeColumn = makeColumn;
exports.make = make;
/* ReasonReact Not a pure module */
