// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var React = require("react");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");
var Option$Rationale = require("rationale/src/Option.js");

function apolloResponseToResult(result) {
  if (typeof result === "number") {
    return /* Error */Block.__(1, [React.createElement("div", undefined, "Loading")]);
  } else if (result.tag) {
    return /* Ok */Block.__(0, [result[0]]);
  } else {
    return /* Error */Block.__(1, [React.createElement("div", undefined, "WHAT?")]);
  }
}

function filterOptionalResult(errorMessage, result) {
  if (result !== undefined) {
    return /* Ok */Block.__(0, [Js_primitive.valFromOption(result)]);
  } else {
    return /* Error */Block.__(1, [errorMessage]);
  }
}

function ste(prim) {
  return prim;
}

function idd(e) {
  return e;
}

function catOptionals(optionals) {
  return optionals.filter(Option$Rationale.isSome).map((function (param) {
                return Option$Rationale.toExn("", param);
              }));
}

exports.apolloResponseToResult = apolloResponseToResult;
exports.filterOptionalResult = filterOptionalResult;
exports.ste = ste;
exports.idd = idd;
exports.catOptionals = catOptionals;
/* react Not a pure module */
