// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Js_dict = require("bs-platform/lib/js/js_dict.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var HandsOnTable$Client = require("../../utils/HandsOnTable.bs.js");
var UseRouterForLinks$Client = require("../../utils/UseRouterForLinks.bs.js");

var component = ReasonReact.statelessComponent("MeasurableTable");

function toUnix(x) {
  return x.createdAt.unix();
}

function make(measurements, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              var data = $$Array.map((function (e) {
                      return Js_dict.fromList(/* :: */[
                                  /* tuple */[
                                    "createdAt",
                                    e[/* createdAt */3].format("L, h:mm:ss a")
                                  ],
                                  /* [] */0
                                ]);
                    }), measurements);
              var columns = /* array */[
                HandsOnTable$Client.makeColumn("createdAt", undefined, undefined, /* () */0),
                HandsOnTable$Client.makeColumn("competitive", undefined, undefined, /* () */0),
                HandsOnTable$Client.makeColumn("percentile25", undefined, undefined, /* () */0),
                HandsOnTable$Client.makeColumn("percentile50", undefined, undefined, /* () */0),
                HandsOnTable$Client.makeColumn("percentile75", undefined, undefined, /* () */0)
              ];
              var colHeaders = /* array */[
                "Created at",
                "competitive",
                "25th",
                "50th",
                "75th"
              ];
              return ReasonReact.element(undefined, undefined, UseRouterForLinks$Client.make(/* array */[ReasonReact.element(undefined, undefined, HandsOnTable$Client.make(data, columns, colHeaders, /* array */[]))]));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.toUnix = toUnix;
exports.make = make;
/* component Not a pure module */
