const MEASUREMENT_TYPE = {
    floatCdf: 'FLOAT_CDF',
    floatPoint: 'FLOAT_POINT',
    percentage: 'PERCENTAGE',
    binary: 'BINARY',
};

const SCORING_MARKET_TYPE = {
    MARKET: 'MARKET',
    NON_MARKET: 'NON_MARKET'
};

let SCORING_PAIR = {
    FLOAT_CDF_PREDICTION_FLOAT_POINT_RESULT: "FLOAT_CDF_PREDICTION_FLOAT_POINT_RESULT",
    FLOAT_CDF_PREDICTION_FLOAT_CDF_RESULT: "FLOAT_CDF_PREDICTION_FLOAT_CDF_RESULT",
    PERCENTAGE_PREDICTION_PERCENTAGE_RESULT: "PERCENTAGE_PREDICTION_PERCENTAGE_RESULT",
    INVALID: "INVALID"
};

module.exports = {
 MEASUREMENT_TYPE,
 SCORING_MARKET_TYPE,
 SCORING_PAIR,
};