const TEMPLATE_NAME = {
  MEASURABLE_STATE_IS_CHANGED: 'MEASURABLE_STATE_IS_CHANGED',
  MEASURABLE_STATE_IS_RESOLVED: 'MEASURABLE_STATE_IS_RESOLVED',
  MEMBER_ADDED_TO_COMMUNITY: 'MEMBER_ADDED_TO_COMMUNITY',
  MEMBER_INVITED_TO_COMMUNITY: 'MEMBER_INVITED_TO_COMMUNITY',
  MEMBER_JOINED_COMMUNITY_FEED_ITEM: 'MEMBER_JOINED_COMMUNITY_FEED_ITEM',
  NEW_MEASUREMENT_PREDICTION_FEED_ITEM: 'NEW_MEASUREMENT_PREDICTION_FEED_ITEM',
  NEW_MEASUREMENT_COMMENT_FEED_ITEM: 'NEW_MEASUREMENT_COMMENT_FEED_ITEM',
  NEW_MEASUREMENT_RESOLUTION_FEED_ITEM: 'NEW_MEASUREMENT_RESOLUTION_FEED_ITEM',
  NEW_MEASUREMENT_RESOLUTION_NOT_AVAILABLE_FEED_ITEM: 'NEW_MEASUREMENT_RESOLUTION_NOT_AVAILABLE_FEED_ITEM',
  MEASURABLE_REACHED_RESOLUTION_DATE_FEED_ITEM: 'MEASURABLE_REACHED_RESOLUTION_DATE_FEED_ITEM',
  NEW_MEASURABLE_FEED_ITEM: 'NEW_MEASURABLE_FEED_ITEM',
  NEW_CHANNEL_FEED_ITEM: 'NEW_CHANNEL_FEED_ITEM',
  NEW_INVITATION: 'NEW_INVITATION',
};

module.exports = {
  TEMPLATE_NAME,
};
