/* Untyped file generated by genType. */

const $$toJS104575624 = {"909067767": "GENERIC", "-527079426": "QUESTION_FEEDBACK", "965227017": "UPDATE"};

import * as MeasurementValueBS from './MeasurementValue.bs';

export const Comment_fromString = function (Arg1) {
  const result = MeasurementValueBS.Comment[0](Arg1);
  return $$toJS104575624[result]
};
