// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");

var list_to_array = $$Array.of_list;

exports.list_to_array = list_to_array;
/* No side effect */
