// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Curry = require("bs-platform/lib/js/curry.js");

function allTrue(e) {
  return $$Array.fold_left((function (x, y) {
                if (x) {
                  return y;
                } else {
                  return false;
                }
              }), true, e);
}

function MakeByPercentile(Item) {
  var isValid = function (byPercentile) {
    var itemsAreValid = allTrue($$Array.map((function (param) {
                return Curry._1(Item[/* isValid */1], param[1]);
              }), byPercentile));
    if (itemsAreValid) {
      return true;
    } else {
      return false;
    }
  };
  return /* module */[/* isValid */isValid];
}

function equal(a, b) {
  return a === b;
}

function isValid() {
  return true;
}

var Float = /* module */[
  /* equal */equal,
  /* isValid */isValid
];

function equal$1(a, b) {
  return a === b;
}

function isValid$1(e) {
  if (e >= 0) {
    return e <= 100;
  } else {
    return false;
  }
}

var Percentage = /* module */[
  /* equal */equal$1,
  /* isValid */isValid$1
];

function isValid$2(byPercentile) {
  var itemsAreValid = allTrue($$Array.map((function () {
              return true;
            }), byPercentile));
  if (itemsAreValid) {
    return true;
  } else {
    return false;
  }
}

var Bar = /* module */[/* isValid */isValid$2];

exports.allTrue = allTrue;
exports.MakeByPercentile = MakeByPercentile;
exports.Float = Float;
exports.Percentage = Percentage;
exports.Bar = Bar;
/* No side effect */
