// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");
var Json_encode = require("@glennsl/bs-json/src/Json_encode.bs.js");

function parseTrio(json) {
  return /* record */[
          /* p25 */Json_decode.field("p25", Json_decode.$$float, json),
          /* p50 */Json_decode.field("p50", Json_decode.$$float, json),
          /* p75 */Json_decode.field("p75", Json_decode.$$float, json)
        ];
}

function encodeTrio(trio) {
  return Json_encode.object_(/* :: */[
              /* tuple */[
                "p25",
                trio[/* p25 */0]
              ],
              /* :: */[
                /* tuple */[
                  "p50",
                  trio[/* p50 */1]
                ],
                /* :: */[
                  /* tuple */[
                    "p75",
                    trio[/* p75 */2]
                  ],
                  /* [] */0
                ]
              ]
            ]);
}

function parseValue(json) {
  var trio = Json_decode.optional((function (param) {
          return Json_decode.field("trio", parseTrio, param);
        }), json);
  var point = Json_decode.optional((function (param) {
          return Json_decode.field("point", Json_decode.$$float, param);
        }), json);
  if (trio !== undefined) {
    if (point !== undefined) {
      return /* Trio */Block.__(0, [/* record */[
                  /* p25 */0.0,
                  /* p50 */0.0,
                  /* p75 */0.0
                ]]);
    } else {
      return /* Trio */Block.__(0, [trio]);
    }
  } else if (point !== undefined) {
    return /* Point */Block.__(1, [point]);
  } else {
    return /* Trio */Block.__(0, [/* record */[
                /* p25 */0.0,
                /* p50 */0.0,
                /* p75 */0.0
              ]]);
  }
}

function encodeValue(value) {
  if (value.tag) {
    return "";
  } else {
    return Json_encode.object_(/* :: */[
                /* tuple */[
                  "trio",
                  encodeTrio(value[0])
                ],
                /* [] */0
              ]);
  }
}

exports.parseTrio = parseTrio;
exports.encodeTrio = encodeTrio;
exports.parseValue = parseValue;
exports.encodeValue = encodeValue;
/* Json_encode Not a pure module */
