// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Belt_Id = require("bs-platform/lib/js/belt_Id.js");
var Js_dict = require("bs-platform/lib/js/js_dict.js");
var Belt_Map = require("bs-platform/lib/js/belt_Map.js");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");
var Caml_format = require("bs-platform/lib/js/caml_format.js");
var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");
var Json_encode = require("@glennsl/bs-json/src/Json_encode.bs.js");

function allTrue(e) {
  return $$Array.fold_left((function (x, y) {
                if (x) {
                  return y;
                } else {
                  return false;
                }
              }), true, e);
}

function MakeByPercentile(Item) {
  var cmp = Caml_obj.caml_compare;
  var Id = Belt_Id.MakeComparable(/* module */[/* cmp */cmp]);
  var name = Item[/* itemName */3] + "ByPercentile";
  var hasQuartiles = function (t) {
    if (Belt_Map.has(t, 25.0) && Belt_Map.has(t, 50.0)) {
      return Belt_Map.has(t, 75.0);
    } else {
      return false;
    }
  };
  var toArray = Belt_Map.toArray;
  var toDict = function (t) {
    return Js_dict.fromArray($$Array.map((function (param) {
                      return /* tuple */[
                              Pervasives.string_of_float(param[0]),
                              param[1]
                            ];
                    }), Belt_Map.toArray(t)));
  };
  var fromArray = function (a) {
    return (function (param) {
                return Belt_Map.fromArray(param, Id);
              })(a);
  };
  var fromDict = function (r) {
    return (function (param) {
                return Belt_Map.fromArray(param, Id);
              })($$Array.map((function (param) {
                      return /* tuple */[
                              Caml_format.caml_float_of_string(param[0]),
                              param[1]
                            ];
                    }), Js_dict.entries(r)));
  };
  var decode = function (json) {
    var partial_arg = Item[/* decodeFn */5];
    return fromDict(Json_decode.field("data", (function (param) {
                      return Json_decode.dict(partial_arg, param);
                    }), json));
  };
  var encode = function (t) {
    var dic = toDict(t);
    return Json_encode.object_(/* :: */[
                /* tuple */[
                  "dataType",
                  name
                ],
                /* :: */[
                  /* tuple */[
                    "data",
                    Js_dict.map((function (value) {
                            return Curry._1(Item[/* encodeFn */4], value);
                          }), dic)
                  ],
                  /* [] */0
                ]
              ]);
  };
  return /* module */[
          /* Id */Id,
          /* name */name,
          /* hasQuartiles */hasQuartiles,
          /* toArray */toArray,
          /* toDict */toDict,
          /* fromArray */fromArray,
          /* fromDict */fromDict,
          /* decode */decode,
          /* encode */encode
        ];
}

function makeDecode(decodeFn, json) {
  return Json_decode.field("data", decodeFn, json);
}

function makeEncode(encodeFn, name, i) {
  return Json_encode.object_(/* :: */[
              /* tuple */[
                "dataType",
                name
              ],
              /* :: */[
                /* tuple */[
                  "data",
                  Curry._1(encodeFn, i)
                ],
                /* [] */0
              ]
            ]);
}

var itemName = "float";

var name = "floatPoint";

function equal(a, b) {
  return a === b;
}

function isValid() {
  return true;
}

function encodeFn(prim) {
  return prim;
}

function decode(param) {
  return Json_decode.field("data", Json_decode.$$float, param);
}

function encode(param) {
  return makeEncode(encodeFn, name, param);
}

var FloatPoint = /* module */[
  /* itemName */itemName,
  /* name */name,
  /* equal */equal,
  /* isValid */isValid,
  /* decodeFn */Json_decode.$$float,
  /* encodeFn */encodeFn,
  /* decode */decode,
  /* encode */encode
];

var itemName$1 = "dateTime";

var name$1 = "dateTimePoint";

function equal$1(a, b) {
  return a === b;
}

function isValid$1() {
  return true;
}

function encodeFn$1(prim) {
  return prim;
}

function decode$1(param) {
  return Json_decode.field("data", Json_decode.string, param);
}

function encode$1(param) {
  return makeEncode(encodeFn$1, name$1, param);
}

var DateTimePoint = /* module */[
  /* itemName */itemName$1,
  /* name */name$1,
  /* equal */equal$1,
  /* isValid */isValid$1,
  /* encodeFn */encodeFn$1,
  /* decodeFn */Json_decode.string,
  /* decode */decode$1,
  /* encode */encode$1
];

var cmp = Caml_obj.caml_compare;

var Id = Belt_Id.MakeComparable(/* module */[/* cmp */cmp]);

var name$2 = "floatByPercentile";

function hasQuartiles(t) {
  if (Belt_Map.has(t, 25.0) && Belt_Map.has(t, 50.0)) {
    return Belt_Map.has(t, 75.0);
  } else {
    return false;
  }
}

var toArray = Belt_Map.toArray;

function toDict(t) {
  return Js_dict.fromArray($$Array.map((function (param) {
                    return /* tuple */[
                            Pervasives.string_of_float(param[0]),
                            param[1]
                          ];
                  }), Belt_Map.toArray(t)));
}

function fromArray(a) {
  return (function (param) {
              return Belt_Map.fromArray(param, Id);
            })(a);
}

function fromDict(r) {
  return (function (param) {
              return Belt_Map.fromArray(param, Id);
            })($$Array.map((function (param) {
                    return /* tuple */[
                            Caml_format.caml_float_of_string(param[0]),
                            param[1]
                          ];
                  }), Js_dict.entries(r)));
}

function decode$2(json) {
  return fromDict(Json_decode.field("data", (function (param) {
                    return Json_decode.dict(Json_decode.$$float, param);
                  }), json));
}

function encode$2(t) {
  var dic = toDict(t);
  return Json_encode.object_(/* :: */[
              /* tuple */[
                "dataType",
                name$2
              ],
              /* :: */[
                /* tuple */[
                  "data",
                  Js_dict.map((function (value) {
                          return value;
                        }), dic)
                ],
                /* [] */0
              ]
            ]);
}

var FloatPercentiles = /* module */[
  /* Id */Id,
  /* name */name$2,
  /* hasQuartiles */hasQuartiles,
  /* toArray */toArray,
  /* toDict */toDict,
  /* fromArray */fromArray,
  /* fromDict */fromDict,
  /* decode */decode$2,
  /* encode */encode$2
];

var cmp$1 = Caml_obj.caml_compare;

var Id$1 = Belt_Id.MakeComparable(/* module */[/* cmp */cmp$1]);

var name$3 = "dateTimeByPercentile";

function hasQuartiles$1(t) {
  if (Belt_Map.has(t, 25.0) && Belt_Map.has(t, 50.0)) {
    return Belt_Map.has(t, 75.0);
  } else {
    return false;
  }
}

var toArray$1 = Belt_Map.toArray;

function toDict$1(t) {
  return Js_dict.fromArray($$Array.map((function (param) {
                    return /* tuple */[
                            Pervasives.string_of_float(param[0]),
                            param[1]
                          ];
                  }), Belt_Map.toArray(t)));
}

function fromArray$1(a) {
  return (function (param) {
              return Belt_Map.fromArray(param, Id$1);
            })(a);
}

function fromDict$1(r) {
  return (function (param) {
              return Belt_Map.fromArray(param, Id$1);
            })($$Array.map((function (param) {
                    return /* tuple */[
                            Caml_format.caml_float_of_string(param[0]),
                            param[1]
                          ];
                  }), Js_dict.entries(r)));
}

function decode$3(json) {
  return fromDict$1(Json_decode.field("data", (function (param) {
                    return Json_decode.dict(Json_decode.string, param);
                  }), json));
}

function encode$3(t) {
  var dic = toDict$1(t);
  return Json_encode.object_(/* :: */[
              /* tuple */[
                "dataType",
                name$3
              ],
              /* :: */[
                /* tuple */[
                  "data",
                  Js_dict.map((function (value) {
                          return value;
                        }), dic)
                ],
                /* [] */0
              ]
            ]);
}

var DateTimePercentiles = /* module */[
  /* Id */Id$1,
  /* name */name$3,
  /* hasQuartiles */hasQuartiles$1,
  /* toArray */toArray$1,
  /* toDict */toDict$1,
  /* fromArray */fromArray$1,
  /* fromDict */fromDict$1,
  /* decode */decode$3,
  /* encode */encode$3
];

var name$4 = "percentage";

function isValid$2(i) {
  if (i <= 0.0) {
    return i <= 100.0;
  } else {
    return false;
  }
}

function encodeFn$2(prim) {
  return prim;
}

function decode$4(param) {
  return Json_decode.field("data", Json_decode.$$float, param);
}

function encode$4(param) {
  return makeEncode(encodeFn$2, name$4, param);
}

var Percentage = /* module */[
  /* name */name$4,
  /* isValid */isValid$2,
  /* decodeFn */Json_decode.$$float,
  /* encodeFn */encodeFn$2,
  /* decode */decode$4,
  /* encode */encode$4
];

var name$5 = "binary";

function isValid$3(i) {
  if (i === 0) {
    return true;
  } else {
    return i === 1;
  }
}

function encodeFn$3(prim) {
  return prim;
}

function decode$5(param) {
  return Json_decode.field("data", Json_decode.$$int, param);
}

function encode$5(param) {
  return makeEncode(encodeFn$3, name$5, param);
}

var Binary = /* module */[
  /* name */name$5,
  /* isValid */isValid$3,
  /* decodeFn */Json_decode.$$int,
  /* encodeFn */encodeFn$3,
  /* decode */decode$5,
  /* encode */encode$5
];

function decode$6(json) {
  var t = Json_decode.field("dataType", Json_decode.string, json);
  if (t === name) {
    return /* FloatPoint */Block.__(0, [Json_decode.field("data", Json_decode.$$float, json)]);
  } else if (t === name$1) {
    return /* DateTimePoint */Block.__(2, [Json_decode.field("data", Json_decode.string, json)]);
  } else if (t === name$4) {
    return /* Percentage */Block.__(4, [Json_decode.field("data", Json_decode.$$float, json)]);
  } else if (t === name$5) {
    return /* Binary */Block.__(5, [Json_decode.field("data", Json_decode.$$int, json)]);
  } else if (t === name$3) {
    return /* DateTimePercentiles */Block.__(3, [decode$3(json)]);
  } else if (t === name$2) {
    return /* FloatPercentiles */Block.__(1, [decode$2(json)]);
  } else {
    return /* FloatPoint */Block.__(0, [0.1]);
  }
}

function encodee(t) {
  switch (t.tag | 0) {
    case 0 : 
        return makeEncode(encodeFn, name, t[0]);
    case 1 : 
        return encode$2(t[0]);
    case 2 : 
        return makeEncode(encodeFn$1, name$1, t[0]);
    case 3 : 
        return encode$3(t[0]);
    case 4 : 
        return makeEncode(encodeFn$2, name$4, t[0]);
    case 5 : 
        return makeEncode(encodeFn$3, name$5, t[0]);
    
  }
}

var data = "data";

var dataType = "dataType";

exports.allTrue = allTrue;
exports.data = data;
exports.dataType = dataType;
exports.MakeByPercentile = MakeByPercentile;
exports.makeDecode = makeDecode;
exports.makeEncode = makeEncode;
exports.FloatPoint = FloatPoint;
exports.DateTimePoint = DateTimePoint;
exports.FloatPercentiles = FloatPercentiles;
exports.DateTimePercentiles = DateTimePercentiles;
exports.Percentage = Percentage;
exports.Binary = Binary;
exports.decode = decode$6;
exports.encodee = encodee;
/* Id Not a pure module */
