/* Untyped file generated by genType. */

import * as CreateBucklescriptBlock from 'bs-platform/lib/es6/block.js';

import * as Graph_TBS from './Graph_T.bs';

export const T_String = function _(Arg1) { return CreateBucklescriptBlock.__(0, [Arg1]) }

export const T_ThingId = function _(Arg1) { return CreateBucklescriptBlock.__(1, [Arg1]) }

export const T_JSON = function _(Arg1) { return CreateBucklescriptBlock.__(2, [Arg1]) }

export const T_Fact = function _(Arg1) { return CreateBucklescriptBlock.__(0, [[Arg1.thingIdString, Arg1.subjectId, Arg1.propertyId, [Arg1.value.valueType]]]) }

export const T_Item = 0;

export const T_SUBJECT = 0;

export const T_PROPERTY = 1;

export const T_VALUE = 2;

export const Thing_to_s = function _(Arg1) { const result = Graph_TBS.Thing[1]([[Arg1.thingId.thingIdString, Arg1.thingId.isPublic, Arg1.thingId.baseId], Arg1.thingType]); return result };

export const Thing_to_json = function _(Arg1) { const result = Graph_TBS.Thing[2]([[Arg1.thingId.thingIdString, Arg1.thingId.isPublic, Arg1.thingId.baseId], Arg1.thingType]); return result };
