module.exports = {
  // Sync Signals
  EVERY_HOUR: 'EVERY_HOUR',
  EVERY_TEN_MINUTES: 'EVERY_TEN_MINUTES',
  EVERY_MINUTE: 'EVERY_MINUTE',

  // Encapsulated Events Flow
  MAIL: 'MAIL',

  // System Events
  NEW_MEASUREMENT: 'NEW_MEASUREMENT',
  NEW_MEASURABLE: 'NEW_MEASURABLE',
  NEW_MEMBERSHIP: 'NEW_MEMBERSHIP',
  MEASURABLE_CHANGED: 'MEASURABLE_CHANGED',
};
