module.exports = {
  // Sync Signals
  EVERY_HOUR: 'EVERY_HOUR',
  EVERY_TEN_MINUTES: 'EVERY_TEN_MINUTES',
  EVERY_MINUTE: 'EVERY_MINUTE',

  // Encapsulated Events Flow
  MAIL: 'MAIL',

  // System Events
  MEASURABLE_STATE_IS_CHANGED: 'MEASURABLE_STATE_IS_CHANGED',
  MEASURABLE_STATE_IS_RESOLVED: 'MEASURABLE_STATE_IS_RESOLVED',
  MEMBER_ADDED_TO_COMMUNITY: 'MEMBER_ADDED_TO_COMMUNITY',
  MEMBER_INVITED_TO_COMMUNITY: 'MEMBER_INVITED_TO_COMMUNITY',
  MEMBER_JOINED_COMMUNITY: 'MEMBER_JOINED_COMMUNITY',
  NEW_MEASUREMENT: 'NEW_MEASUREMENT',
  NEW_MEASURABLE: 'NEW_MEASURABLE',
};
