/* Untyped file generated by genType. */

import * as InterfaceBS from './Interface.bs';

export const Graph_fromJson = InterfaceBS.Graph[0];

export const Graph_things = InterfaceBS.Graph[1];

export const Graph_facts = InterfaceBS.Graph[2];

export const Graph_factList = InterfaceBS.Graph[3];

export const Graph_directoryArray = InterfaceBS.Graph[4];

export const Graph_childDirectories = InterfaceBS.Graph[5];

export const Graph_rootDirectories = InterfaceBS.Graph[6];

export const Graph_findThing = InterfaceBS.Graph[7];

export const Graph_findThingFromFact = InterfaceBS.Graph[8];

export const Graph_to_json = InterfaceBS.Graph[9];

export const Graph_EdgeTypes_property = InterfaceBS.Graph[10][0];

export const Graph_EdgeTypes_subject = InterfaceBS.Graph[10][1];

export const Thing_to_json = InterfaceBS.Thing[0];

export const Directory_parent = InterfaceBS.Directory[0];

export const Fact_to_json = InterfaceBS.Fact[0];

export const Fact_value = InterfaceBS.Fact[1];

export const Filter_query = InterfaceBS.Filter[0];

export const Query_from_json = InterfaceBS.Query[0];

export const Value_to_json = InterfaceBS.Value[0];

export const list_to_array = InterfaceBS.list_to_array;
